// Generated by scripts/stamp-logo.sh from assets/logo.svg. Do not edit by hand;
// swap the icon by replacing assets/logo.svg and re-running the script.
enum Logo {
    static let svg = #"""
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
  <path d="M3.5 9.5c0-2.8 2.2-5 5-5 2.6 0 4.6 1.8 5 4.3.3 2 .5 3.5 2 5.2l-2.9 2.3c-1.2 1-2.7 1.5-4.3 1.2-3-.5-4.8-4-4.8-8Z"/>
  <path d="M15.5 14 20.5 7.5"/>
  <path d="M3.5 9.5H1"/>
  <path d="M6 8h.01"/>
  <path d="M8.5 17.5V21"/>
  <path d="M12 17.2V21"/>
</svg>
"""#
}
