#!/bin/sh
# Stamp assets/logo.svg into Sources/wren/Logo.generated.swift so the
# binary stays single-file (no resource bundle). Run standalone after swapping
# the icon, or let scripts/dev.sh call it before every build.
set -e

cd "$(dirname "$0")/.."

{
    echo "// Generated by scripts/stamp-logo.sh from assets/logo.svg. Do not edit by hand;"
    echo "// swap the icon by replacing assets/logo.svg and re-running the script."
    echo "enum Logo {"
    echo "    static let svg = #\"\"\""
    cat assets/logo.svg
    echo "\"\"\"#"
    echo "}"
} > daemon/Sources/wren/Logo.generated.swift
